export const products = [
  {
    productId: 1,
    desc: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    brand: "Apple",
    color: "Siyah",
    colorEn: "black",
    image: "images/productImages/image1.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 2,
    desc: "Apple iPhone 11",
    brand: "Apple",
    color: "Sarı",
    colorEn: "yellow",
    image: "images/productImages/image2.png",
    price: "800,85",
    actualPrice: "900,00",
    sale: "2%",
  },
  {
    productId: 3,
    desc: "iPhone 11 Kırmızı Kılıf",
    brand: "Apple",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image3.png",
    price: "127,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 4,
    desc: "Samsung Telefon",
    brand: "Samsung",
    color: "Sarı",
    colorEn: "yellow",
    image: "images/productImages/image4.png",
    price: "155,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Samsung Telefon 1",
    brand: "Samsung",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image2.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Xiaomi Redmi Note 10S 128 GB 6 GB Ram",
    brand: "Xiomi",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image1.png",
    price: "190,85",
    actualPrice: "130,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Oppo Reno Telefon",
    brand: "Huawei",
    color: "Sarı",
    colorEn: "yellow",
    image: "images/productImages/image2.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Xiomi Telefon",
    brand: "Huawei",
    color: "Mor",
    colorEn: "purple",
    image: "images/productImages/image4.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Oppo Reno 5 Lite 128 GB",
    brand: "Oppo Reno",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image2.png",
    price: "310,85",
    actualPrice: "224,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image1.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Apple Telefon",
    brand: "Apple",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image3.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image4.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image4.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "HTC Desire 20 Pro",
    brand: "HTC",
    color: "Sarı",
    colorEn: "yellow",
    image: "images/productImages/image2.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 5,
    desc: "Huawei Telefon",
    brand: "Huawei",
    color: "Kırmızı",
    colorEn: "red",
    image: "images/productImages/image1.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
];
