export const products = [
  {
    productId: 1,
    desc: "Apple iPhone 11 Pro Maxi Phone 11 Pro Max iPhone 11 (Max 2 Line)",
    brand: "Apple",
    color: "Siyah",
    image: "images/productImages/image 1.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 2,
    desc: "Apple iPhone 11",
    brand: "Apple",
    color: "Sarı",
    image: "images/productImages/image 1.png",
    price: "800,85",
    actualPrice: "900,00",
    sale: "2%",
  },
  {
    productId: 3,
    desc: "iPhone 11 Kırmızı Kılıf",
    brand: "Apple",
    color: "Kırmızı",
    image: "images/productImages/image 1.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
  {
    productId: 4,
    desc: "Apple Telefon",
    brand: "Apple",
    color: "Sarı",
    image: "images/productImages/image 1.png",
    price: "90,85",
    actualPrice: "124,00",
    sale: "12%",
  },
];
